pipeline {
    agent any
    stages {
        stage ('checkout') {
            steps {
                git branch: 'main', credentialsId: 'Github_login', url: 'https://github.com/mukthiyarglobal/React_Azure_appservices.git'
            }
        }
        stage ('azure_login') {
            steps {
                script {
		   azureCLI commands: [[exportVariablesString: '', script: '']], principalCredentialId: 'azure_loginid'
		} 
            }
        }
        stage ('terraform init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }
        stage ('terraform plan') {
            steps {
                dir('Terraform') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                script {
                    // Request user input (Yes/No)
                    def userInput = input(
                        id: 'userInput',
                        message: 'Do you want to apply the Terraform changes?',
                        parameters: [choice(choices: ['Yes', 'No'], description: 'Select Yes or No', name: 'Proceed')]
                    )
 
                    // Check user input
                    if (userInput == 'Yes') {
                        // Execute terraform apply
                        sh 'terraform apply tfplan'
                    } else {
                        echo 'Terraform apply skipped as per user choice.'
                    }
                }
            }
        }
    }
}











