pipeline {
    agent any
    stages {
        stage ('checkout') {
            steps {
                git branch: 'main', credentialsId: 'Github_login', url: 'https://github.com/mukthiyarglobal/React_Azure_appservices.git'
            }
        }
        stage ('azure_login') {
            steps {
                script {
				    azureCLI commands: [[exportVariablesString: '', script: '']], principalCredentialId: 'azure_loginid'
				} 
            }
        }
        stage ('terraform init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }
        stage ('terraform plan') {
            steps {
                dir('Terraform') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage ('terraform action') {
            steps {
                dir('Terraform') {
                     echo "Terraform action is --> ${action}"
                     sh ('terraform ${action} --auto-approve') 
                }
            }
        }
    }
}











